In [1]:
import numpy as np
import pandas as pd
import seaborn as sns

In [2]:
#Створено Дата Фрейм
df = pd.read_csv('survey_results_public.csv')
df2 = pd.read_csv('survey_results_schema.csv')

In [3]:
df.head()

,ResponseId,MainBranch,Age,Employment,RemoteWork,Check,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,...,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,SurveyLength,SurveyEase,ConvertedCompYearly,JobSat
0,1,I am a developer by profession,Under 18 years old,"Employed, full-time",Remote,Apples,Hobby,Primary/elementary school,Books / Physical media,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,I am a developer by profession,35-44 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects;Other...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,...,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
2,3,I am a developer by profession,45-54 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects;Other...,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,...,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN,NaN
3,4,I am learning to code,18-24 years old,"Student, full-time",NaN,Apples,NaN,Some college/university study without earning ...,"Other online resources (e.g., videos, blogs, f...",Stack Overflow;How-to videos;Interactive tutorial,...,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Easy,NaN,NaN
4,5,I am a developer by profession,18-24 years old,"Student, full-time",NaN,Apples,NaN,"Secondary school (e.g. American high school, G...","Other online resources (e.g., videos, blogs, f...",Technical documentation;Blogs;Written Tutorial...,...,NaN,NaN,NaN,NaN,NaN,NaN,Too short,Easy,NaN,NaN

In [4]:
#1. Загальна кількість користувачів, які взяли участь в опитуванні Stack Overflow

count_respons = df['ResponseId'].size
count_respons

65437

In [5]:
#Перетворення у список

questions = df2['qname'].tolist()

In [6]:
#Отримання списку питань 

stuck = []
for q in questions:
    if q in df.columns:
        stuck.append(q)
questions = stuck 
print(questions)

['MainBranch', 'Age', 'Employment', 'RemoteWork', 'Check', 'CodingActivities', 'EdLevel', 'LearnCode', 'LearnCodeOnline', 'TechDoc', 'YearsCode', 'YearsCodePro', 'DevType', 'OrgSize', 'PurchaseInfluence', 'BuyNewTool', 'BuildvsBuy', 'TechEndorse', 'Country', 'Currency', 'CompTotal', 'NEWSOSites', 'SOVisitFreq', 'SOAccount', 'SOPartFreq', 'SOHow', 'SOComm', 'AISelect', 'AISent', 'AIBen', 'AIAcc', 'AIComplex', 'AIThreat', 'AIEthics', 'AIChallenges', 'TBranch', 'ICorPM', 'WorkExp', 'TimeSearching', 'TimeAnswering', 'Frustration', 'ProfessionalTech', 'ProfessionalCloud', 'ProfessionalQuestion', 'Industry', 'JobSat', 'SurveyLength', 'SurveyEase', 'Knowledge_1', 'Knowledge_2', 'Knowledge_3', 'Knowledge_4', 'Knowledge_5', 'Knowledge_6', 'Knowledge_7', 'Knowledge_8', 'Knowledge_9', 'Frequency_1', 'Frequency_2', 'Frequency_3', 'JobSatPoints_1', 'JobSatPoints_4', 'JobSatPoints_5', 'JobSatPoints_6', 'JobSatPoints_7', 'JobSatPoints_8', 'JobSatPoints_9', 'JobSatPoints_10', 'JobSatPoints_11']

In [7]:
#Перевірка на наявність відповідей на ці питання у кожного респондента
check_all = df[questions].notna().all(axis = 1)
check_all

0        False
1        False
2        False
3        False
4        False
         ...
65432    False
65433    False
65434    False
65435    False
65436    False
Length: 65437, dtype: bool

In [8]:
#Кількість респондентів без пропущених значень
count_all = check_all.sum()
count_all

np.int64(6306)

In [9]:
# Обчислення не пропущенних значень

non_missing_values = df['WorkExp'].count()
non_missing_values

np.int64(29658)

In [10]:
# Обчислення пропущенних значень

missing_values = df['WorkExp'].isna().sum()
missing_values

np.int64(35779)

In [11]:
#Середнє значення (mean)
#Медіана (median)
#Мода (mode)

mean_ = df['WorkExp'].mean()
median_ = df['WorkExp'].median()
mode_ = df['WorkExp'].mode()

In [12]:
df['WorkExp'].describe()

count    29658.000000
mean        11.466957
std          9.168709
min          0.000000
25%          4.000000
50%          9.000000
75%         16.000000
max         50.000000
Name: WorkExp, dtype: float64

In [13]:
#Виведення результатів

print(mean_)
print(median_)
print(mode_)

11.46695663901814
9.0
0    3.0
Name: WorkExp, dtype: float64

In [14]:
## Аналіз формату роботи розробників
#За допомогою циклу `for` виконано перебір значень у стовпці та підраховано кількість записів зі значенням `"Remote"`.

rem = 0
for w in df['RemoteWork']:
    if w == 'Remote':
         rem +=1
rem

20831

In [15]:
#Aналіз розподілу форматів роботи респондентів за допомогою методу `value_counts()`, включаючи пропущені значення.

df['RemoteWork'].value_counts(dropna=False)

RemoteWork
Hybrid (some remote, some in-person)    23015
Remote                                  20831
In-person                               10960
NaN                                     10631
Name: count, dtype: int64

In [16]:
#Перевірка на наявність Python у колонці 'LanguageHaveWorkedWith' та підрахунок кількості респондентів, які програмують на Python

python_users = df['LanguageHaveWorkedWith'].fillna('').str.contains('Python').sum()
python_users

np.int64(30795)

In [17]:
# Підраховано кількість непорожніх значень у колонці `LanguageHaveWorkedWith`+
# обчислено відсоток користувачів Python серед усіх респондентів.
total = df['LanguageHaveWorkedWith'].notna().sum()
percentage = (python_users/total)*100
percentage

np.float64(51.54406226462466)

In [18]:
#Перевірка на наявність 'Online Courses or Certification' у колонці 'LearnCode'
#та підрахунок кількості респондентів , які обрали онлайн курси.

courses = df['LearnCode'].fillna('').str.contains('Online Courses or Certification').sum()
courses

np.int64(30271)

In [19]:
#Стіорюємо дф, де залишаємо тілки тих респондентів, що використовують Python
python = df['LanguageHaveWorkedWith'].fillna('').str.contains('Python')

In [20]:
# створюємо копію 
df_python = df[python].copy()
df_python

,ResponseId,MainBranch,Age,Employment,RemoteWork,Check,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,...,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,SurveyLength,SurveyEase,ConvertedCompYearly,JobSat
1,2,I am a developer by profession,35-44 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects;Other...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,...,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
3,4,I am learning to code,18-24 years old,"Student, full-time",NaN,Apples,NaN,Some college/university study without earning ...,"Other online resources (e.g., videos, blogs, f...",Stack Overflow;How-to videos;Interactive tutorial,...,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Easy,NaN,NaN
4,5,I am a developer by profession,18-24 years old,"Student, full-time",NaN,Apples,NaN,"Secondary school (e.g. American high school, G...","Other online resources (e.g., videos, blogs, f...",Technical documentation;Blogs;Written Tutorial...,...,NaN,NaN,NaN,NaN,NaN,NaN,Too short,Easy,NaN,NaN
5,6,I code primarily as a hobby,Under 18 years old,"Student, full-time",NaN,Apples,NaN,Primary/elementary school,"School (i.e., University, College, etc);Online...",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN,NaN
10,11,"I used to be a developer by profession, but no...",35-44 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Other online resources ...,Technical documentation;Books;Written Tutorial...,...,25.0,10.0,0.0,15.0,0.0,0.0,Appropriate in length,Easy,NaN,8.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65421,65422,I am a developer by profession,25-34 years old,"Employed, full-time",Remote,Apples,I don’t code outside of work,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65427,65428,"I am not primarily a developer, but I write co...",25-34 years old,"Not employed, but looking for work;Employed, p...",In-person,Apples,Hobby;Professional development or self-paced l...,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65431,65432,I am a developer by profession,45-54 years old,"Employed, full-time","Hybrid (some remote, some in-person)",Apples,Hobby;Contribute to open-source projects;Profe...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65435,65436,I am a developer by profession,18-24 years old,"Employed, full-time","Hybrid (some remote, some in-person)",Apples,Hobby;Contribute to open-source projects;Profe...,"Secondary school (e.g. American high school, G...",On the job training;Other online resources (e....,Technical documentation;Blogs;Written Tutorial...,...,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
65436,65437,I code primarily as a hobby,18-24 years old,"Student, full-time",NaN,Apples,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [21]:
# Підготовка даних для аналізу заробітної плати
#Для подальшого аналізу рівня заробітної плати значення у колонці `ConvertedCompYearly` було перетворено у числовий формат.
#Параметр `errors='coerce'` використано для автоматичної заміни некоректних або текстових значень на `NaN`, 
#що дозволяє коректно виконувати статистичний аналіз даних.

df_python['ConvertedCompYearly'] = pd.to_numeric(df_python['ConvertedCompYearly'], errors = 'coerce')

In [22]:
#Групуємо значення за країнами та підраховуємо 'mean','median'
result = df_python.groupby('Country')['ConvertedCompYearly'].agg(['mean','median'])
result

                                               mean    median
Country
Afghanistan                             4543.000000    4768.5
Albania                                56295.000000   56295.0
Algeria                                 9053.285714    6230.0
Andorra                               193331.000000  193331.0
Angola                                     6.000000       6.0
...                                             ...       ...
Venezuela, Bolivarian Republic of...   21500.000000    7100.0
Viet Nam                               14014.562500   10180.0
Yemen                                  10297.333333    5333.0
Zambia                                 28123.666667   22803.0
Zimbabwe                               37500.000000   18000.0

[173 rows x 2 columns]

In [23]:
#Обрано колонки з інформацією про рівень освіти та заробітну плату, видалено пропущені значення, 
#виконано сортування даних за спаданням заробітної плати, визначено топ-5 респондентів із найвищим доходом.
    
df_top_5 = df[['EdLevel','ConvertedCompYearly']].dropna().sort_values(by = 'ConvertedCompYearly', ascending = False).head(5)
df_top_5

                                              EdLevel  ConvertedCompYearly
15837    Bachelor’s degree (B.A., B.S., B.Eng., etc.)           16256603.0
12723  Professional degree (JD, MD, Ph.D, Ed.D, etc.)           13818022.0
28379  Professional degree (JD, MD, Ph.D, Ed.D, etc.)            9000000.0
17593    Bachelor’s degree (B.A., B.S., B.Eng., etc.)            6340564.0
17672  Professional degree (JD, MD, Ph.D, Ed.D, etc.)            4936778.0

In [24]:
#Для кожної вікової категорії визначила відсоток респондентів, які програмують на Python.
#Це дасть уявлення про те, в яких вікових групах Python є найпопулярнішим.

In [25]:
p = df[df['LanguageHaveWorkedWith'].fillna('').str.contains('Python')]

In [26]:
df_new = p.copy()

In [27]:
p

,ResponseId,MainBranch,Age,Employment,RemoteWork,Check,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,...,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,SurveyLength,SurveyEase,ConvertedCompYearly,JobSat
1,2,I am a developer by profession,35-44 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects;Other...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,...,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
3,4,I am learning to code,18-24 years old,"Student, full-time",NaN,Apples,NaN,Some college/university study without earning ...,"Other online resources (e.g., videos, blogs, f...",Stack Overflow;How-to videos;Interactive tutorial,...,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Easy,NaN,NaN
4,5,I am a developer by profession,18-24 years old,"Student, full-time",NaN,Apples,NaN,"Secondary school (e.g. American high school, G...","Other online resources (e.g., videos, blogs, f...",Technical documentation;Blogs;Written Tutorial...,...,NaN,NaN,NaN,NaN,NaN,NaN,Too short,Easy,NaN,NaN
5,6,I code primarily as a hobby,Under 18 years old,"Student, full-time",NaN,Apples,NaN,Primary/elementary school,"School (i.e., University, College, etc);Online...",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN,NaN
10,11,"I used to be a developer by profession, but no...",35-44 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Other online resources ...,Technical documentation;Books;Written Tutorial...,...,25.0,10.0,0.0,15.0,0.0,0.0,Appropriate in length,Easy,NaN,8.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65421,65422,I am a developer by profession,25-34 years old,"Employed, full-time",Remote,Apples,I don’t code outside of work,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65427,65428,"I am not primarily a developer, but I write co...",25-34 years old,"Not employed, but looking for work;Employed, p...",In-person,Apples,Hobby;Professional development or self-paced l...,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65431,65432,I am a developer by profession,45-54 years old,"Employed, full-time","Hybrid (some remote, some in-person)",Apples,Hobby;Contribute to open-source projects;Profe...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65435,65436,I am a developer by profession,18-24 years old,"Employed, full-time","Hybrid (some remote, some in-person)",Apples,Hobby;Contribute to open-source projects;Profe...,"Secondary school (e.g. American high school, G...",On the job training;Other online resources (e....,Technical documentation;Blogs;Written Tutorial...,...,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
65436,65437,I code primarily as a hobby,18-24 years old,"Student, full-time",NaN,Apples,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [28]:
#Виконано очищення даних від пропущених значень у колонці `Age` для подальшого аналізу віку респондентів.

age_all = df.dropna(subset = ['Age'])
age_p = p.dropna(subset = ['Age'])

In [29]:
#Виконано групування респондентів за віком та підрахунок кількості користувачів у кожній віковій категорії.

total = age_all.groupby(['Age']).size()
python_use = age_p.groupby(['Age']).size()

In [30]:
#Підрахували відсоток респондентів
percentage_python = (python_use/total) * 100

In [31]:
percentage_python

Age
18-24 years old       55.922826
25-34 years old       45.773912
35-44 years old       41.520546
45-54 years old       41.910706
55-64 years old       40.427184
65 years or older     37.564767
Prefer not to say     45.341615
Under 18 years old    64.875389
dtype: float64